apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: disaster-system
type: Opaque
stringData:
  username: disaster
  password: disasterpass
  host: amqp://rabbitmq.disaster-system.svc.cluster.local:5672/
  vhostName: /
